# Generated by Django 4.0.3 on 2022-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Venue',
            field=models.CharField(default='NULL', max_length=13),
        ),
    ]
