# Generated by Django 4.0.3 on 2022-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_bookings_room_alter_bookings_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Room',
            field=models.CharField(default='Null', max_length=6),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Venue',
            field=models.CharField(default='NULL', max_length=1),
        ),
    ]
